### ISSUE TITLE
Use simple templates for the messages the bot answers

### ISSUE THREAD

**Issue by meodai** [meodai/colorparrot-twitter-bot#31]
Would be nice to have a json that contains all the messages the bot answers or uses. (Would also be nice if there are multiple possible answers per action possible, that are randomly selected )

**Comment by jnafolayan** [comment]
done. implemented a system to generate a message by compiling a random pick from pre-made templates.

**Comment by meodai** [comment]
@jnafolayan https://github.com/meodai/colorparrot-twitter-bot/blob/master/src/templates.json ? So having more then one in the array, will choose one of them?

**Comment by jnafolayan** [comment]
Affirmative.
