### ISSUE TITLE
feat: Make it possible to ask for a color name by providing an image

### ISSUE THREAD

**Issue by meodai** [meodai/colorparrot-twitter-bot#33]
Would be cool if you can say something like hey @color_parot, what color is this? And post an image? Or maybe just tag color_parot as a person on the picture to get the name of the dominant color back. (https://www.npmjs.com/package/dominant-color)

**Comment by jnafolayan** [comment]
Implemented `what color is this?` for tweets, replies, and quoted replies.

**Comment by meodai** [comment]
this is pretty cool! I tested it on a bunch of scenarios. 
But I think it should not respond with the Original Image, but just the color swatch.
![image](https://user-images.githubusercontent.com/608386/110111466-a885f700-7db0-11eb-90c0-7233107a830a.png)
or maybe both? In the second case, when there are multiple images, make sure to only include the picture the color was taken from: https://twitter.com/color_parrot/status/1367622594757853186

**Comment by jnafolayan** [comment]
done. the bot is now responding with the swatch.
