### ISSUE TITLE
update response if hex value exists in color-names

### ISSUE THREAD

**Issue by NikolayKrishchuk** [meodai/colorparrot-twitter-bot#9]
when user asks bot:
@color_parrot super pink #c99f99
example response:
"#c99f99 is reserved already. Choose another hex"

**Comment by meodai** [comment]
@NikolayKrishchuk the message should be "Darn! #c99f99 is taken already. Try shifting the values a bit and try again"

**Comment by NikolayKrishchuk** [comment]
done
